### ISSUE TITLE
Installing from pip fails due to dependencies

### ISSUE THREAD

**Issue by FieldData** [1hada/rosbag-merge#4]
pip3 install rosbag-merge

Collecting rosbag-merge
  Using cached rosbag_merge-0.0.7-py3-none-any.whl (18 kB)
  Using cached rosbag_merge-0.0.6-py3-none-any.whl (17 kB)
  Using cached rosbag_merge-0.0.4-py3-none-any.whl (17 kB)
  Using cached rosbag_merge-0.0.2-py3-none-any.whl (17 kB)
  Using cached rosbag_merge-0.0.1-py3-none-any.whl (17 kB)
ERROR: Cannot install rosbag-merge==0.0.1, rosbag-merge==0.0.2, rosbag-merge==0.0.4, rosbag-merge==0.0.6 and rosbag-merge==0.0.7 because these package versions have conflicting dependencies.

The conflict is caused by:
    rosbag-merge 0.0.7 depends on rosbag
    rosbag-merge 0.0.6 depends on rosbag
    rosbag-merge 0.0.4 depends on rosbag
    rosbag-merge 0.0.2 depends on rosbag
    rosbag-merge 0.0.1 depends on rosbag

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by 1hada** [comment]
@FieldData , thanks for pointing this out! I'll be looking into it in the coming week.

**Comment by 1hada** [comment]
Hello @FieldData , I've decided to remove the version requirements so that pip can automatically resolve them.
Can you please confirm whether the newly published `rosbag-merge` now installs more smoothly for you?

**Comment by MartinCorto** [comment]
Hello @1hada,

I have the same issue on the package installation.

I'll tried to use "pip3 install rosbag-merge==0.0.9" 

Collecting rosbag-merge==0.0.9
  Using cached rosbag_merge-0.0.9-py3-none-any.whl (18 kB)
Collecting dask
  Using cached dask-2023.3.2-py3-none-any.whl (1.2 MB)
Collecting icecream
  Using cached icecream-2.1.3-py2.py3-none-any.whl (8.4 kB)
Collecting pandas
  Using cached pandas-2.0.0-cp311-cp311-win_amd64.whl (11.2 MB)
ERROR: Could not find a version that satisfies the requirement rosbag (from rosbag-merge) (from versions: none)
ERROR: No matching distribution found for rosbag

**Comment by 1hada** [comment]
@MartinCorto , I believe this recommendation will solve the issue you're seeing (_not having the python packages for ROS_).
In order to resolve that you may need to install ROS.
Currently `rosbag-merge` only support Ubuntu, if people need it for Windows I can consider making those updates/ recommend another package.
- http://wiki.ros.org/noetic/Installation/Ubuntu

If you already have ROS Noetic installed, you will first need to source it, then install rosbag-merge.
- `source /opt/ros/noetic/setup.bash`


Here's an example
```
(rosbag-merge-venv) $ pip3 install rosbag-merge==0.0.9
Collecting rosbag-merge==0.0.9
  Using cached rosbag_merge-0.0.9-py3-none-any.whl (18 kB)
Collecting dask
  Downloading dask-2023.4.0-py3-none-any.whl (1.2 MB)
     |████████████████████████████████| 1.2 MB 3.5 MB/s
Collecting pandas
  Using cached pandas-2.0.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.3 MB)
Collecting icecream
  Using cached icecream-2.1.3-py2.py3-none-any.whl (8.4 kB)
ERROR: Could not find a version that satisfies the requirement rosbag (from rosbag-merge==0.0.9) (from versions: none)
ERROR: No matching distribution found for rosbag (from rosbag-merge==0.0.9)
(rosbag-merge-venv) $ pip3 install rosbag-merge
Collecting rosbag-merge
  Using cached rosbag_merge-0.0.9-py3-none-any.whl (18 kB)
Collecting icecream
  Using cached icecream-2.1.3-py2.py3-none-any.whl (8.4 kB)
ERROR: Could not find a version that satisfies the requirement rospy (from rosbag-merge) (from versions: none)
ERROR: No matching distribution found for rospy (from rosbag-merge)
(rosbag-merge-venv) $ pip3 install
 rospy
ERROR: Could not find a version that satisfies the requirement rospy (from versions: none)
ERROR: No matching distribution found for rospy
(rosbag-merge-venv) $ source /opt/ros/noetic/setup.bash
(rosbag-merge-venv) $ pip3 install rospy
Requirement already satisfied: rospy in /opt/ros/noetic/lib/python3/dist-packages (1.15.15)
(rosbag-merge-venv) $ pip3 install rosbag-merge==0.0.9
Collecting rosbag-merge==0.0.9
  Using cached rosbag_merge-0.0.9-py3-none-any.whl (18 kB)
Collecting icecream
  Using cached icecream-2.1.3-py2.py3-none-any.whl (8.4 kB)
Collecting tqdm
  Using cached tqdm-4.65.0-py3-none-any.whl (77 kB)
Requirement already satisfied: rospy in /opt/ros/noetic/lib/python3/dist-packages (from rosbag-merge==0.0.9) (1.15.15)
Collecting dask
  Using cached dask-2023.4.0-py3-none-any.whl (1.2 MB)
Requirement already satisfied: rosbag in /opt/ros/noetic/lib/python3/dist-packages (from rosbag-merge==0.0.9) (1.15.15)
Collecting pandas
  Using cached pandas-2.0.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.3 MB)
Collecting colorama>=0.3.9
  Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting executing>=0.3.1
  Downloading executing-1.2.0-py2.py3-none-any.whl (24 kB)
Collecting asttokens>=2.0.1
  Downloading asttokens-2.2.1-py2.py3-none-any.whl (26 kB)
Collecting pygments>=2.2.0
  Downloading Pygments-2.15.0-py3-none-any.whl (1.1 MB)
     |████████████████████████████████| 1.1 MB 6.9 MB/s
Collecting toolz>=0.8.2
  Downloading toolz-0.12.0-py3-none-any.whl (55 kB)
     |████████████████████████████████| 55 kB 6.0 MB/s
Collecting pyyaml>=5.3.1
  Downloading PyYAML-6.0-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (701 kB)
     |████████████████████████████████| 701 kB 14.0 MB/s
Collecting fsspec>=0.6.0
  Downloading fsspec-2023.4.0-py3-none-any.whl (153 kB)
     |████████████████████████████████| 153 kB 36.7 MB/s
Collecting importlib-metadata>=4.13.0
  Downloading importlib_metadata-6.4.1-py3-none-any.whl (22 kB)
Collecting click>=7.0
  Downloading click-8.1.3-py3-none-any.whl (96 kB)
     |████████████████████████████████| 96 kB 9.3 MB/s
Collecting partd>=1.2.0
  Downloading partd-1.4.0-py3-none-any.whl (18 kB)
Collecting cloudpickle>=1.1.1
  Downloading cloudpickle-2.2.1-py3-none-any.whl (25 kB)
Collecting packaging>=20.0
  Downloading packaging-23.1-py3-none-any.whl (48 kB)
     |████████████████████████████████| 48 kB 11.9 MB/s
Collecting python-dateutil>=2.8.2
  Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
     |████████████████████████████████| 247 kB 89.3 MB/s
Collecting pytz>=2020.1
  Downloading pytz-2023.3-py2.py3-none-any.whl (502 kB)
     |████████████████████████████████| 502 kB 21.0 MB/s
Collecting numpy>=1.20.3; python_version < "3.10"
  Downloading numpy-1.24.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
     |████████████████████████████████| 17.3 MB 767 kB/s
Collecting tzdata>=2022.1
  Downloading tzdata-2023.3-py2.py3-none-any.whl (341 kB)
     |████████████████████████████████| 341 kB 13.4 MB/s
Collecting six
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting zipp>=0.5
  Downloading zipp-3.15.0-py3-none-any.whl (6.8 kB)
Collecting locket
  Downloading locket-1.0.0-py2.py3-none-any.whl (4.4 kB)
Installing collected packages: colorama, executing, six, asttokens, pygments, icecream, tqdm, toolz, pyyaml, fsspec, zipp, importlib-metadata, click, locket, partd, cloudpickle, packaging, dask, python-dateutil, pytz, numpy, tzdata, pandas, rosbag-merge
Successfully installed asttokens-2.2.1 click-8.1.3 cloudpickle-2.2.1 colorama-0.4.6 dask-2023.4.0 executing-1.2.0 fsspec-2023.4.0 icecream-2.1.3 importlib-metadata-6.4.1 locket-1.0.0 numpy-1.24.2 packaging-23.1 pandas-2.0.0 partd-1.4.0 pygments-2.15.0 python-dateutil-2.8.2 pytz-2023.3 pyyaml-6.0 rosbag-merge-0.0.9 six-1.16.0 toolz-0.12.0 tqdm-4.65.0 tzdata-2023.3 zipp-3.15.0
```

**Comment by MartinCorto** [comment]
Hi @1hada,
Thanks for your answer, unfortunaly i'm working on windows and i can't install ubuntu easily at work. I didn't see your package was only supported by ubuntu.

**Comment by 1hada** [comment]
@MartinCorto , can you install via pip and test again?
- I tested on my side and believe I reformatted everything to remove the ros and ubuntu dependency.

I recommend using the python api if using Windows, here's an example which shows how :
- https://github.com/1hada/rosbag-merge/blob/7d2d8443d414bbd05886600b43cba4b03ee5c08f/examples/main_direct.py#L7
Hope that helps.

**Comment by MartinCorto** [comment]
Script is working, thanks for your help.

**Comment by 1hada** [comment]
@FieldData , when testing for windows I found the same issue you did.

closing because I believe the current fix prevents the dependency issues.
- let me know if you need more help. 

Enjoy!
